package lk.aurelia.Gui;

import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.UIManager;
import lk.aurelia.connection.MySQL;
import raven.toast.Notifications;
import lk.aurelia.Validation.Validation;
import lk.aurelia.model.userDetails;

/**
 *
 * @author DamithaB
 */
public class SignIn extends javax.swing.JFrame {

    
    
    public SignIn() {
        initComponents();
        Notifications.getInstance().setJFrame(this);
        this.setBackground(new Color(0, 0, 0, 0));
        ImageIcon icon = new ImageIcon(getClass().getResource("/lk/aurelia/img/AureliaLogo48px.png"));
        this.setIconImage(icon.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background2 = new lk.aurelia.component.Background();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        emailField = new lk.aurelia.component.RoundTextField();
        signInButton = new lk.aurelia.component.RoundButton();
        passwordField = new lk.aurelia.component.RoundPasswordField();
        background1 = new lk.aurelia.component.Background();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        background2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(4, 79, 118));
        jLabel5.setText("Email");

        jLabel6.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(4, 79, 118));
        jLabel6.setText("Password");

        emailField.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12)); // NOI18N

        signInButton.setBackground(new java.awt.Color(207, 227, 238));
        signInButton.setForeground(new java.awt.Color(4, 79, 118));
        signInButton.setText("Sign In");
        signInButton.setBorderPainted(false);
        signInButton.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 15)); // NOI18N
        signInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signInButtonActionPerformed(evt);
            }
        });

        passwordField.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12)); // NOI18N

        background1.setBackground(new java.awt.Color(207, 227, 238));
        background1.setForeground(new java.awt.Color(207, 227, 238));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/aurelia/img/AureliaLogo - White Round 100px.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 18)); // NOI18N
        jLabel1.setText("Welcome to");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Aurelia Hospital ");

        javax.swing.GroupLayout background1Layout = new javax.swing.GroupLayout(background1);
        background1.setLayout(background1Layout);
        background1Layout.setHorizontalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background1Layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addGap(44, 44, 44))
        );
        background1Layout.setVerticalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout background2Layout = new javax.swing.GroupLayout(background2);
        background2.setLayout(background2Layout);
        background2Layout.setHorizontalGroup(
            background2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background2Layout.createSequentialGroup()
                .addGroup(background2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(background2Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(background2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(background2Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(signInButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(background1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        background2Layout.setVerticalGroup(
            background2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background2Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(signInButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(background2Layout.createSequentialGroup()
                .addComponent(background1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void signInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signInButtonActionPerformed
        String email = emailField.getText();
        String password = String.valueOf(passwordField.getPassword());

        if (emailValidation(email)) {
            return;
        }

        if (passwordValidation(password)) {
            return;
        }

        try {
            ResultSet getUser = MySQL.search("SELECT * FROM `user_details` "
                    + "WHERE `email`='" + email + "' AND `password`='" + password + "'");

            if (getUser.next()) {
                if (getUser.getInt("status_id") == 1) {

                    userDetails ud = new userDetails();
                    ud.setId(getUser.getString("id"));
                    ud.setFname(getUser.getString("fname"));
                    ud.setLname(getUser.getString("lname"));

                    if (getUser.getInt("user_type_id") == 1) {
                        //loadAdmin
                        new AdminDashboard(ud).setVisible(true);
                        this.dispose();
                    } else if (getUser.getInt("user_type_id") == 2) {
                        //loadDoctor
                        new DoctorDashboard(ud).setVisible(true);
                        this.dispose();
                    } else if (getUser.getInt("user_type_id") == 3) {
                        //loadReception
                        new ReceptionDashboard(ud).setVisible(true);
                        this.dispose();
                    } else if (getUser.getInt("user_type_id") == 4) {
                        //loadItManagement
                        new ManagerDashboard(ud).setVisible(true);
                        this.dispose();
                    } else if (getUser.getInt("user_type_id") == 5) {
                        //loadTheater
                        new TheaterDashboard(ud).setVisible(true);
                        this.dispose();
                    } else if (getUser.getInt("user_type_id") == 6) {
                        //loadPharmacist
                        new PharmacistDashboard(ud).setVisible(true);
                        this.dispose();
                    }

                } else {
                    //Deactivated User
                    Notifications.getInstance().show(Notifications.Type.WARNING, Notifications.Location.TOP_RIGHT, "This user has temporarily Deactivated!");
                }

            } else {
                //Invalid userName or password
                Notifications.getInstance().show(Notifications.Type.WARNING, Notifications.Location.TOP_RIGHT, "Invalid Email or Password");
            }

        } catch (SQLException e) {
            throw new RuntimeException(e);
        }

    }//GEN-LAST:event_signInButtonActionPerformed

    private boolean emailValidation(String value) {
        if (value.isEmpty()) {
            Notifications.getInstance().show(Notifications.Type.WARNING, Notifications.Location.TOP_RIGHT, "Email Cannot Be empty!");
            return true;
        } else if (!value.matches(Validation.EMAIL_VALIDATION.validate())) {
            Notifications.getInstance().show(Notifications.Type.WARNING, Notifications.Location.TOP_RIGHT, "Invalid Email!");
            return true;
        }

        return false;
    }

    private boolean passwordValidation(String value) {
        if (value.isEmpty()) {
            Notifications.getInstance().show(Notifications.Type.WARNING, Notifications.Location.TOP_RIGHT, "Password cannot be empty!");
            return true;
        } else if (!value.matches(Validation.PASSWORD_VALIDATION.validate())) {
            Notifications.getInstance().show(Notifications.Type.WARNING, Notifications.Location.TOP_RIGHT, "Invalid Password!");
            return true;
        }
        return false;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            //load the theme
            UIManager.setLookAndFeel(new FlatLightLaf());

        } catch (Exception ex) {
            ex.printStackTrace();
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private lk.aurelia.component.Background background1;
    private lk.aurelia.component.Background background2;
    private lk.aurelia.component.RoundTextField emailField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private lk.aurelia.component.RoundPasswordField passwordField;
    private lk.aurelia.component.RoundButton signInButton;
    // End of variables declaration//GEN-END:variables
}
