/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package lk.aurelia.Panel;

import lk.aurelia.component.table.TableCustom;

/**
 *
 * @author aloka
 */
public class PharmacistStockPanel extends javax.swing.JPanel {

    /**
     * Creates new form PharmacistStockPanel
     */
    public PharmacistStockPanel() {
        initComponents();
        
        TableCustom.apply(jScrollPane1, TableCustom.TableType.MULTI_LINE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        searchButton = new lk.aurelia.component.RoundButton();
        pharmacistField4 = new lk.aurelia.component.RoundTextField();
        jLabel15 = new javax.swing.JLabel();
        addButton = new lk.aurelia.component.RoundButton();
        addButton1 = new lk.aurelia.component.RoundButton();
        printButton = new lk.aurelia.component.RoundButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Stock ID", "Grn_Item_Id", "Brand", "Category", "Qty", "Unit Price", "Selling Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        searchButton.setBackground(new java.awt.Color(211, 231, 240));
        searchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/aurelia/img/search 16x16.png"))); // NOI18N
        searchButton.setText("Search");
        searchButton.setBorderPainted(false);
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        pharmacistField4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        pharmacistField4.setPreferredSize(new java.awt.Dimension(180, 25));

        jLabel15.setText("Selling Price");

        addButton.setBackground(new java.awt.Color(4, 79, 118));
        addButton.setForeground(new java.awt.Color(255, 255, 255));
        addButton.setText("Add Stock");
        addButton.setBorderPainted(false);
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        addButton1.setBackground(new java.awt.Color(0, 102, 102));
        addButton1.setForeground(new java.awt.Color(255, 255, 255));
        addButton1.setText("Update Stock");
        addButton1.setBorderPainted(false);
        addButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButton1ActionPerformed(evt);
            }
        });

        printButton.setBackground(new java.awt.Color(211, 231, 240));
        printButton.setText("Print Stock");
        printButton.setBorderPainted(false);
        printButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(printButton, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pharmacistField4, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                        .addGap(137, 137, 137)
                        .addComponent(addButton, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(260, 260, 260)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(printButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pharmacistField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed

    }//GEN-LAST:event_searchButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        //        pharmacistBarcode = String.valueOf(System.currentTimeMillis()) + "_" + "PH";
        //        String fname = pharmacistField1.getText();
        //        String lname = pharmacistField2.getText();
        //        String email = pharmacistField3.getText();
        //        String password = String.valueOf(passwordField.getPassword());
        //        String status = String.valueOf(pharmacyCombo.getSelectedItem());
        //        String mobile = pharmacistField4.getText();
        //        String address = pharmacistField6.getText();
      
    }//GEN-LAST:event_addButtonActionPerformed

    private void addButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButton1ActionPerformed
        //        int selectedRow = jTable1.getSelectedRow();
        //        if (selectedRow == -1) {
            //            Notifications.getInstance().show(Notifications.Type.WARNING, Notifications.Location.TOP_RIGHT, "Please Select a Row First");
            //        } else {
            //            String fname = pharmacistField1.getText();
            //            String lname = pharmacistField2.getText();
            //            String mobile = pharmacistField4.getText();
            //            String status = String.valueOf(pharmacyCombo.getSelectedItem());
            //            String address = pharmacistField6.getText();
            //
            //            if (fname.isEmpty()) {
                //                Notifications.getInstance().show(Notifications.Type.WARNING, Notifications.Location.TOP_RIGHT, "First name is Required ");
                //            } else if (lname.isBlank()) {
                //                Notifications.getInstance().show(Notifications.Type.WARNING, Notifications.Location.TOP_RIGHT, "Last name is Required ");
                //
                //            } else if (mobile.isEmpty()) {
                //                Notifications.getInstance().show(Notifications.Type.WARNING, Notifications.Location.TOP_RIGHT, "Mobile is Required ");
                //
                //            } else if (!mobile.matches(Validation.MOBILE_VALIDATION.validate())) {
                //                Notifications.getInstance().show(Notifications.Type.WARNING, Notifications.Location.TOP_RIGHT, "Please Enter a Valid Mobile ");
                //
                //            } else if (status.equals("Select")) {
                //                Notifications.getInstance().show(Notifications.Type.WARNING, Notifications.Location.TOP_RIGHT, "Please Select a Type ");
                //
                //            } else if (address.isEmpty()) {
                //                Notifications.getInstance().show(Notifications.Type.WARNING, Notifications.Location.TOP_RIGHT, "Address is Required ");
                //
                //            } else {
                //                try {
                    //                    int statusId = pharmacistStatusMap.get(status);
                    //                    MySQL.iud("UPDATE `user_details` INNER JOIN `pharmacist` ON `pharmacist`.user_details_id = user_details.id SET `fname` = '" + fname + "',`lname`='" + lname + "',`mobile`='" + mobile + "'"
                        //                        + ",`address` = '" + address + "',`status_id` = '" + statusId + "' WHERE `pharmacist`.barcode  = '" + String.valueOf(jTable1.getValueAt(selectedRow, 0)) + "' ");
                    //
                    //                    reset();
                    //                    activeField();
                    //                    Notifications.getInstance().show(Notifications.Type.SUCCESS, Notifications.Location.TOP_RIGHT, "Updated Successfully");
                    //
                    //                } catch (SQLException e) {
                    //                    logger.warning(e.getMessage());
                    //                }
                //            }
            //        }
    }//GEN-LAST:event_addButton1ActionPerformed

    private void printButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printButtonActionPerformed

//        InputStream stream = getClass().getResourceAsStream("/lk/aurelia/reports/pharmesist_report.jasper");
//
//        try {
//            SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
//            String date = format.format(new Date());
//            HashMap<String, Object> parameters = new HashMap<>();
//            parameters.put("name", managerName);
//            parameters.put("date_txt", date);
//
//            JRTableModelDataSource dataSource = new JRTableModelDataSource(jTable1.getModel());
//            JasperPrint print = JasperFillManager.fillReport(stream, parameters, dataSource);
//            JasperViewer.viewReport(print, false);
//
//        } catch (JRException ex) {
//            logger.warning(ex.getMessage());
//        }

    }//GEN-LAST:event_printButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private lk.aurelia.component.RoundButton addButton;
    private lk.aurelia.component.RoundButton addButton1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private lk.aurelia.component.RoundTextField pharmacistField4;
    private lk.aurelia.component.RoundButton printButton;
    private lk.aurelia.component.RoundButton searchButton;
    // End of variables declaration//GEN-END:variables
}
