/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package lk.aurelia.Panel;

import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Vector;
import java.util.logging.FileHandler;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import lk.aurelia.Gui.ReceptionDashboard;
import lk.aurelia.component.table.TableCustom;
import lk.aurelia.connection.MySQL;
import net.sf.jasperreports.engine.JRDataSource;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.data.JRTableModelDataSource;
import net.sf.jasperreports.view.JasperViewer;
import raven.toast.Notifications;

/**
 *
 * @author Huawei
 */
public class ReceptionPatientShedulePanel extends javax.swing.JPanel {

    private ReceptionDashboard dashboard;
    private Logger logger;
    private FileHandler handler;

    /**
     * Creates new form ReceptionPatientShedulePanel
     */
    public ReceptionPatientShedulePanel(ReceptionDashboard receptionDashboard) {
        initComponents();
        dashboard = receptionDashboard;
        try {
            logger = Logger.getLogger(ManageTheaterPanel.class.getName());
            handler = new FileHandler(ManageTheaterPanel.class.getName() + ".log", true);
            logger.addHandler(handler);
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
//        TableCustom.apply(jScrollPane1, TableCustom.TableType.MULTI_LINE);
        Notifications.getInstance().setJFrame(dashboard);
        TableCustom.apply(scrollPanel, TableCustom.TableType.MULTI_LINE);
        loadPatientTable("");
    }

    private void loadPatientTable(String search) {
        try {
            ResultSet rs = MySQL.search("SELECT * FROM `schedule` INNER JOIN `doctor_has_schedule` ON "
                    + "`schedule`.`id`=`doctor_has_schedule`.`schedule_id` INNER JOIN `doctor` ON "
                    + "`doctor`.`barcode`=`doctor_has_schedule`.`doctor_barcode` INNER JOIN `user_details` ON "
                    + "`user_details`.`id`=`doctor`.`user_details_id` INNER JOIN `doctor_type` ON `doctor_type`.`id`=`doctor`.`doctor_type_id` "
                    + "WHERE `type` LIKE '%" + search + "%' OR `fname` LIKE '%" + search + "%' OR `lname` LIKE '%" + search + "%' OR"
                    + "`start_time` LIKE '%" + search + "%' OR `end_time` LIKE '%" + search + "%' OR `date` LIKE '%" + search + "%'");

            DefaultTableModel model = (DefaultTableModel) sheduleTable.getModel();
            model.setRowCount(0);

            while (rs.next()) {
                Vector data = new Vector();
                data.add(rs.getString("type"));
                data.add(rs.getString("fname") + " " + rs.getString("lname"));
                data.add(rs.getString("start_time"));
                data.add(rs.getString("end_time"));
                data.add(rs.getString("date"));
                model.addRow(data);
            }
        } catch (SQLException e) {
            logger.warning(e.getMessage());
        }
    }

    private void updateFields() {
        searchText.setText("");
        loadPatientTable("");
    }

    private void printReport() {
        try {

            SimpleDateFormat dateFormatter = new SimpleDateFormat("yyyy-MM-dd");//("yyyy-MM-dd HH:mm:ss")
            String Joinedate = dateFormatter.format(new Date());

            String Name = dashboard.getShowName().getText();

            HashMap<String, Object> parameters = new HashMap<>();
            parameters.put("reception_name", Name);
            parameters.put("date", Joinedate);

            String filePath = "src//lk//aurelia//reports//doctor_shedule_report.jasper";

            JRDataSource dataSource = new JRTableModelDataSource(sheduleTable.getModel());

            JasperPrint print = JasperFillManager.fillReport(filePath, parameters, dataSource);
            JasperViewer.viewReport(print, false);

        } catch (JRException e) {
            logger.warning(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background1 = new lk.aurelia.component.Background();
        searchText = new lk.aurelia.component.RoundTextField();
        searchButton = new lk.aurelia.component.RoundButton();
        searchButton1 = new lk.aurelia.component.RoundButton();
        scrollPanel = new javax.swing.JScrollPane();
        sheduleTable = new javax.swing.JTable();
        searchButton2 = new lk.aurelia.component.RoundButton();

        searchText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTextActionPerformed(evt);
            }
        });

        searchButton.setBackground(new java.awt.Color(211, 231, 240));
        searchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/aurelia/img/search 16x16.png"))); // NOI18N
        searchButton.setText("Search");
        searchButton.setBorderPainted(false);
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        searchButton1.setBackground(new java.awt.Color(211, 231, 240));
        searchButton1.setForeground(new java.awt.Color(0, 0, 0));
        searchButton1.setText("Reset");
        searchButton1.setBorderPainted(false);
        searchButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButton1ActionPerformed(evt);
            }
        });

        sheduleTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Doctor Type", "Doctor Name", "Start Time", "End Time", "Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollPanel.setViewportView(sheduleTable);

        searchButton2.setBackground(new java.awt.Color(211, 231, 240));
        searchButton2.setForeground(new java.awt.Color(0, 0, 0));
        searchButton2.setText("Print Report");
        searchButton2.setBorderPainted(false);
        searchButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout background1Layout = new javax.swing.GroupLayout(background1);
        background1.setLayout(background1Layout);
        background1Layout.setHorizontalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(background1Layout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(searchText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(148, 148, 148)
                        .addComponent(searchButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(scrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 772, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(searchButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        background1Layout.setVerticalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchTextActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        loadPatientTable(String.valueOf(searchText.getText()));
    }//GEN-LAST:event_searchButtonActionPerformed

    private void searchButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButton1ActionPerformed
        // TODO add your handling code here:
        updateFields();
    }//GEN-LAST:event_searchButton1ActionPerformed

    private void searchButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButton2ActionPerformed
        // TODO add your handling code here:

        printReport();

    }//GEN-LAST:event_searchButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private lk.aurelia.component.Background background1;
    private javax.swing.JScrollPane scrollPanel;
    private lk.aurelia.component.RoundButton searchButton;
    private lk.aurelia.component.RoundButton searchButton1;
    private lk.aurelia.component.RoundButton searchButton2;
    private lk.aurelia.component.RoundTextField searchText;
    private javax.swing.JTable sheduleTable;
    // End of variables declaration//GEN-END:variables
}
